project_id = "yavlicxysspkzvzompph"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[auth]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]
# Functions are deployed to Supabase