import React from 'react';

interface ThreadSummary {
  thread_id: string;
  summary: string;
  key_points: string[];
  model: string;
  created_at: string;
}

interface ThreadSummaryProps {
  summary: ThreadSummary;
}

export function ThreadSummary({ summary }: ThreadSummaryProps) {
  return (
    <div style={{ padding: '1rem', background: '#e8f4ff', borderTop: '1px solid #b3d9ff', marginTop: '1rem' }}>
      <h3 style={{ margin: '0 0 0.5rem 0' }}>Thread Summary</h3>
      <p style={{ margin: '0 0 0.5rem 0' }}>{summary.summary}</p>
      {summary.key_points && summary.key_points.length > 0 && (
        <ul style={{ margin: '0.5rem 0', paddingLeft: '1.5rem' }}>
          {summary.key_points.map((point, index) => (
            <li key={index} style={{ fontSize: '0.9rem', color: '#555' }}>
              {point}
            </li>
          ))}
        </ul>
      )}
      <div style={{ fontSize: '0.75rem', color: '#999' }}>
        Generated by {summary.model} at {new Date(summary.created_at).toLocaleString()}
      </div>
    </div>
  );
}