name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Update NuGet Source with PAT
      if: env.NUGET_GITHUB_PAT != ''
      run: dotnet nuget update source GitHub-Coyoteq1 --username Coyoteq1 --password ${{ secrets.NUGET_GITHUB_PAT }} --store-password-in-clear-text
      env:
        NUGET_GITHUB_PAT: ${{ secrets.NUGET_GITHUB_PAT }}

    - name: Restore dependencies
      run: dotnet restore BattleLuck.sln -p:RestoreLockedMode=false -p:RestorePackagesWithLockFile=true

    - name: Build
      run: dotnet build BattleLuck.sln --configuration Release --no-restore
